name: Android CI/CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x PaprikaAndroid/gradlew

      - name: Build with Gradle
        working-directory: PaprikaAndroid
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: |
          mv PaprikaAndroid/app/build/outputs/apk/release/app-release-unsigned.apk PaprikaAndroid/app/build/outputs/apk/release/PaprikaMessenger.apk
        continue-on-error: true # In case it's named differently or signed

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            PaprikaAndroid/app/build/outputs/apk/release/*.apk
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
